# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the .env file into the working directory
COPY .env .

# Copy the dependencies file to the working directory
COPY ./autogen/requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local scripts directory to the working directory
COPY ./autogen/scripts/ .

CMD ["tail", "-f", "/dev/null"]
